# Generated by Django 3.1.7 on 2021-09-19 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='answered_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answered_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='played_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='games.questions'),
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('played_by', 'answered_for', 'question', 'option')},
        ),
    ]
