# Generated by Django 3.1.7 on 2021-04-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0003_auto_20210411_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='verfication_code',
            new_name='verification_code',
        ),
    ]
