# Generated by Django 3.1.7 on 2021-09-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_auto_20210412_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='email_verification_time',
            new_name='verification_code_timeout',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password_change_time',
        ),
    ]
