# Generated by Django 3.1.7 on 2021-09-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0010_auto_20210918_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemodel',
            name='workspace_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
