# Generated by Django 3.1.7 on 2021-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0013_auto_20210918_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
