# Generated by Django 3.1.7 on 2021-09-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0006_userworkspacerelationtable_workspacemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_workspace_admin',
            field=models.BooleanField(default=False),
        ),
    ]
