# Generated by Django 3.1.7 on 2021-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0007_usermodel_is_workspace_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
