# Generated by Django 3.1.7 on 2021-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0008_usermodel_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemodel',
            name='workspace_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
