# Generated by Django 3.1.7 on 2021-09-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0009_auto_20210918_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userworkspacerelationtable',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userworkspacerelationtable',
            old_name='workspace_id',
            new_name='workspace',
        ),
    ]
