# Generated by Django 3.1.7 on 2021-09-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0011_auto_20210918_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkspacerelationtable',
            name='type_of_user',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Admin User')], max_length=10, null=True),
        ),
    ]
