# Generated by Django 3.1.7 on 2021-09-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0012_auto_20210918_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
