# Generated by Django 3.1.7 on 2021-09-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0014_usermodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
